config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root to: 'places#index'

  resources :users do
    resources :profiles
  end

  resources :map, only: [:index]


  resources :places

  resources :location_managers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
  has_and_belongs_to_many :profiles, through: :language_profiles
  has_many :language_profiles
end

app/models/language_profiles.rb
class LanguageProfile < ActiveRecord::Base
  belongs_to :language
  belongs_to :profile
end

app/models/location_manager.rb
class LocationManager < ApplicationRecord
  belongs_to :user
  belongs_to :place
  validates :user_id, :presence => true, :uniqueness => true


  def self.place_count(value)
    where(place_id: value).count
  end

  def self.user_not_checked_in?(value)
    where(user_id: value).empty?
  end

  def self.user_location(value)
    find_by(user_id: value).place.name
  end

  def self.find_location_entry(value)
    find_by(user_id: value)
  end
end

app/models/place.rb
class Place < ApplicationRecord

  has_many :location_managers
  has_many :users , through: :location_managers

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :languages, through: :language_profiles
  has_many :language_profiles
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_one :profile, dependent: :destroy

  has_many :location_managers
  has_many :places , through: :location_managers

  before_create :build_profile
  accepts_nested_attributes_for :profile

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :load_location_manager

  def load_location_manager
      @location_manager = LocationManager
  end

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/location_managers_controller.rb
class LocationManagersController < ApplicationController

  skip_before_action :verify_authenticity_token, :only => :create

  def create
    LocationManager.create(loc_params)
    redirect_to '/'
  end

  def destroy
    @location_manager_wipe = LocationManager.find(params[:id])
    @location_manager_wipe.destroy
    flash[:notice] = 'You have checked out succesfully'
    redirect_to '/'
  end

  private

  def loc_params
    params.permit(:user_id, :place_id)
  end

  attr_reader :location_manager

end

app/controllers/map_controller.rb
class MapController < ApplicationController

  def index
    @places = Place.all
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  skip_before_action :verify_authenticity_token, :only => :create

  def index
    @places = Place.all
  end

  def show
    @location_managers = LocationManager.where(place_id: params[:id])
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.create(place_params)
      if @place.save
      redirect_to '/places'
    else
      render 'new'
    end
  end

  private

  def place_params
    params.permit(:name, :address, :google_place_id )
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def create
    @user = current_user
    @profile = Profile.find_by(user_id: current_user.id)
  end

  def edit
    @user = current_user
    @profile = Profile.find_by(user_id: current_user.id)
    @languages = Language.all
  end

  def show
    @user = Profile.find_by(user_id: params[:user_id])
    @languages = @user.languages
  end

  def update
    @user = current_user
    @profile = Profile.find_by(user_id: current_user.id)
    if current_user.id != @profile.user_id
      flash[:notice] = "Only owner can update"
      redirect_to '/'
    else
      @profile.update(profile_params)
      redirect_to user_profile_path
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :bio, language_ids:[])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/location_managers_helper.rb
module LocationManagersHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social Code</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav_links">
  <div class="wrapper">

    <a class="logo" href="/">Social Code</a>
    <% if user_signed_in? %>
    <% unless @location_manager.user_not_checked_in?(current_user.id)%>
      <a class="checked_in">You are checked into <%= @location_manager.user_location(current_user.id) %></a>
      <%= link_to 'Check out', location_manager_path(@location_manager.find_location_entry(current_user.id)), method: :delete %>
    <% end %>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      <%= link_to 'Your profile', user_profile_path(current_user.id, current_user.profile.id)%>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
      <% end %>
    </div>
</nav>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/map/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Custom Marker Symbols</title>
    <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
// This example uses SVG path notation to add a vector-based symbol
// as the icon for a marker. The resulting icon is a star-shaped symbol
// with a pale yellow fill and a thick yellow border.

function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 51.525659, lng: -0.0897507},
    zoom: 11
  });

  var infoWindow = new google.maps.InfoWindow();

  var service = new google.maps.places.PlacesService(map);
  <% @places.each do |place| %>
   service.getDetails({
       placeId: '<%= place.google_place_id %>'
   }, function (result, status) {
       var marker = new google.maps.Marker({
           map: map,
           place: {
               placeId: '<%= place.google_place_id %>',
               location: result.geometry.location
           }
       });
       google.maps.event.addListener(marker, 'click', function() {
       service.getDetails(marker.place, function(result, status) {
       if (status !== google.maps.places.PlacesServiceStatus.OK) {
         console.error(status);
         return;
       }
       infoWindow.setContent(result.name);
       infoWindow.open(map, marker);
     });
   });

   });
   <% end %>


}

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyATOWWZzGpccm7Nzj3TpGbxTObrjem_lzg&libraries=places&callback=initMap" async defer>
    </script>

  </body>
</html>

app/views/places/index.html.erb
<br>
<div class='create_place'>
  <%= link_to "Add a Place", new_place_path %>
</div>

<div class='view_map'>
<%= link_to "View locations on Map!", map_index_path %>
</div>


<% if @places.any? %>
<ul>

    <% @places.reverse.each do |place| %>
    <li class='main_list'>
      <div class='places_list'>
      <%= link_to place.name, place_path(place)%>
      <br>
      <br>
      <%= place.address %>
      <br>
      <br>
      Currently here: <%= @location_manager.place_count(place.id) %>
    <br>
    <br>
    <% if current_user && @location_manager.user_not_checked_in?(current_user.id) %>
      <form action='/location_managers' method='post'>
        <input type='hidden' name='user_id' value="<%=current_user.id%>" />
        <input type='hidden' name='place_id' value="<%= place.id %>" />
        <input type='submit' class="button" name='Check in' value='Check in'/>
      </form>
    </div>
    </li>
    <% end %>
    <% end %>

</ul>
  <% else %>
No Places yet
<% end %>

app/views/places/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" src="stylesheets/places.css">
  </head>
  <body>
    <input id="pac-input" class="controls" type="text"
        placeholder="Enter a location">
        <div id="type-selector" class="controls">
          <input type="radio" name="type" id="changetype-all" checked="checked">
          <label for="changetype-all"></label>
        </div>
        <div id="map"></div>
    <div id="map"></div>

    <script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 51.525659, lng: -0.0897507},
          zoom: 13
        });
        var input = /** @type {!HTMLInputElement} */(
            document.getElementById('pac-input'));

        var types = document.getElementById('type-selector');
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(types);

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        var infowindow = new google.maps.InfoWindow();
        var marker = new google.maps.Marker({
          map: map,
          anchorPoint: new google.maps.Point(0, -29)
        });

        autocomplete.addListener('place_changed', function() {
          infowindow.close();
          marker.setVisible(false);
          var place = autocomplete.getPlace();
          if (!place.geometry) {
            window.alert("Please enter another location. This was not found.");
            return;
          }

          // If the place has a geometry, then present it on a map.
          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);  // Why 17? Because it looks good.
          }
          marker.setIcon(/** @type {google.maps.Icon} */({
            url: place.icon,
            size: new google.maps.Size(71, 71),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(35, 35)
          }));
          marker.setPosition(place.geometry.location);
          marker.setVisible(true);

          var address = '';
          if (place.address_components) {
            address = [
              (place.address_components[0] && place.address_components[0].short_name || ''),
              (place.address_components[1] && place.address_components[1].short_name || ''),
              (place.address_components[2] && place.address_components[2].short_name || '')
            ].join(' ');
          }
          console.log(place.address_components)

          infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address + ' ' + '<button class="button" id="save_place">Add Location</button>');
          infowindow.open(map, marker);
          document.getElementById("save_place").addEventListener("click", add_to_db);
          function add_to_db() {
            document.getElementById('formname').value = place.name;
            document.getElementById('formaddress').value = address;
            document.getElementById('placeid').value = place.place_id;
            document.getElementById('form').submit();
          };
        });

        // Sets a listener on a radio button to change the filter type on Places
        // Autocomplete.
        function setupClickListener(id, types) {
          var radioButton = document.getElementById(id);
          radioButton.addEventListener('click', function() {
            autocomplete.setTypes(types);
          });
        }

        setupClickListener('changetype-all', []);
        setupClickListener('changetype-address', ['address']);
        setupClickListener('changetype-establishment', ['establishment']);
        setupClickListener('changetype-geocode', ['geocode']);
      }


    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyATOWWZzGpccm7Nzj3TpGbxTObrjem_lzg&libraries=places&callback=initMap"
        async defer></script>

      <form id="form" action="/places" method="post">
      <input type="hidden" name="name" id="formname" value="">
      <input type="hidden" name="address" id="formaddress" value="">
      <input type="hidden" name="google_place_id" id="placeid" value="">
      <input type="submit" value="Submit">
      </form>

  </body>

</html>

app/views/places/show.html.erb
<div class="user_list">
Currently here: <%= @location_managers.count %>
<% @location_managers.each do |location|  %>
 <br>
 <br>
  <%= link_to location.user.email, user_profile_path(location.user) %>
  <br>
<% end%>
</div>

app/views/profiles/edit.html.erb
<div class='forms'>
  <br>
<%= form_for [@user,@profile] do |form| %>
  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <%= form.label :bio %>
    <%= form.text_field :bio%>
  </div>

  <div class="field">
    <%= form.label "Programming Languages" %><br />
    <%= form.collection_check_boxes :language_ids, Language.all, :id, :language_type do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit :class => "button" %>
  </div>
<% end %>
</div>

app/views/profiles/index.html.erb
This is the profile page

app/views/profiles/show.html.erb
<div class='profile'>
<br>
<br>
Profile Name: <%= @user.name %>
<br>
<br>
Bio: <%= @user.bio %>
<br>
<br>
Languages:
<% if @languages.any? %>
<ul>
    <% @languages.each do |language| %>
    <li>
      <%= language.language_type %>
    </li>
    <% end %>
</ul>
  <% else %>

No Languages selected yet

<% end %>

<br>
<br>

<% if current_user %>
<% if params[:user_id] == current_user.id.to_s %>

<%= link_to 'Edit profile', edit_user_profile_path(current_user.id, current_user.profile.id) %>
<% end %>
<% end %>

</div>

app/views/users/index.html.erb
This is the users index page